### ISSUE TITLE
UI for configuring the API key

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/integration_deepl#1]
Currently requires occ:

    occ config:app:set integration_deepl apikey --value="my-secret-key"

**Comment by samuk** [comment]
What is occ and how do I use it please?

**Comment by joshtrichards** [comment]
@samuk https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html

**Comment by juliushaertl** [comment]
Definitely, should be straight forward to implement. I think most of the other integration apps have good code samples how this can be implemented on the frontend side.

**Comment by juliushaertl** [comment]
Implemented in #7, thanks to @kyteinsky 🎉
