### ISSUE TITLE
Nextcloud 26 Deepl integration Error

### ISSUE THREAD

**Issue by dodofox81** [nextcloud/integration_deepl#3]
Hi,  I have a problem with the  plugin Deepl integration in nextcloud 26. When I have installed and activated, It not work and I found this error in log file:
Error no app in context RuntimeException: Failed to initialize deepl translator class
it's a fresh install of Debian 11, apache2, php 8.1, mariadb

**Comment by joshtrichards** [comment]
From the looks of the code, that error message occurs if you haven't configured the apikey per the README. See the command at the bottom of the page:

https://github.com/juliushaertl/integration_deepl
